const KEY="gestor_comercial_v4";
const el=id=>document.getElementById(id), val=id=>el(id)?.value??"", setText=(id,v)=>{let x=el(id);if(x)x.textContent=v}, setHTML=(id,v)=>{let x=el(id);if(x)x.innerHTML=v};
const today=()=>new Date().toISOString().slice(0,10), monthNow=()=>today().slice(0,7);
const norm=v=>String(v??"").trim().toUpperCase(), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2), money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let db=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}})();
for(const [k,d] of Object.entries({clientes:[],pedidos:[],vendas:[],orcamentos:[],followups:[],alertas:[],apuracaoLinhas:[],apuracaoMetas:[]}))if(!Array.isArray(db[k]))db[k]=d;

function save(renderNow=true){localStorage.setItem(KEY,JSON.stringify(db));if(renderNow)render()}
function num(v){if(typeof v==="number")return v;let s=String(v??"").trim().replace(/R\$/gi,"").replace(/\s/g,"");if(!s)return 0;if(s.includes(",")&&s.includes("."))s=s.replace(/\./g,"").replace(",",".");else if(s.includes(","))s=s.replace(",",".");return Number(s.replace(/[^0-9.-]/g,""))||0}
function dateVal(v){if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==="number"&&window.XLSX){let d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`}let s=String(v??"").trim(),m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;return /^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):""}
function brdate(v){if(!v)return"—";let d=new Date(v+"T12:00:00");return isNaN(d)?String(v):d.toLocaleDateString("pt-BR")}
function header(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g," ").replace(/\s+/g," ").trim()}
function col(headers,aliases){let h=headers.map(header);for(let a of aliases){let n=header(a),i=h.findIndex(x=>x===n);if(i>=0)return i}for(let a of aliases){let n=header(a),i=h.findIndex(x=>x.includes(n)||n.includes(x));if(i>=0)return i}return-1}
function findHeader(raw,required){for(let r=0;r<Math.min(raw.length,60);r++){let h=raw[r].map(header);if(required.every(group=>group.some(a=>h.some(x=>x.includes(header(a))))))return r}return-1}
function clienteById(id){return db.clientes.find(x=>x.id===id)}function clienteByCode(code){return db.clientes.find(x=>String(x.codigo)===String(code))}
function reps(){return [...new Set([...db.clientes.map(x=>x.representante),...db.pedidos.map(x=>x.representante),...db.vendas.map(x=>x.representante)].filter(Boolean))].sort()}
function reg(uf){return ({SP:"Sudeste",RJ:"Sudeste",MG:"Sudeste",ES:"Sudeste",PR:"Sul",SC:"Sul",RS:"Sul",BA:"Nordeste",SE:"Nordeste",AL:"Nordeste",PE:"Nordeste",PB:"Nordeste",RN:"Nordeste",CE:"Nordeste",PI:"Nordeste",MA:"Nordeste",GO:"Centro-Oeste",MT:"Centro-Oeste",MS:"Centro-Oeste",DF:"Centro-Oeste",AM:"Norte",PA:"Norte",AC:"Norte",RO:"Norte",RR:"Norte",AP:"Norte",TO:"Norte"})[norm(uf)]||"Não informado"}
function closeModal(id){el(id)?.classList.remove("open")}

document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");el(b.dataset.tab)?.classList.add("active");setText("pageTitle",b.textContent.replace(/^[^\s]+\s/,""))});
setText("todayText",new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}));
for(const id of ["dashMes","mesVenda","mesPedido"])if(el(id))el(id).value=monthNow();
for(const id of ["dashMes","dashRep","dashRegiao","dashMetric","qCliente","diasCliente","qVenda","mesVenda","qPedido","mesPedido","repPedido","qOrc","statusOrc","qMeta","supMeta","statusMeta"]){let x=el(id);if(x)x.oninput=render}

let charts={};function chart(id,type,labels,data,label,horizontal=false){if(!el(id)||typeof Chart==="undefined")return;if(charts[id])charts[id].destroy();charts[id]=new Chart(el(id),{type,data:{labels,datasets:[{label,data,borderWidth:2,tension:.25}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:horizontal?"y":"x",plugins:{legend:{display:false}},scales:{x:{beginAtZero:true},y:{beginAtZero:true}}}})}

function allSales(){let arr=db.pedidos.map(p=>({id:"P"+p.id,data:p.data,clienteId:p.clienteId,cliente:p.cliente,codigoCliente:p.codigoCliente,representante:p.representante,uf:p.uf,cidade:p.cidade,sem:Number(p.valorSemImpostos??p.valor??0),liq:Number(p.valorLiquido??p.valor??0),origem:"Pedido",ordem:p.ordem,status:p.status}));for(let v of db.vendas)arr.push({id:"V"+v.id,data:v.data,clienteId:v.clienteId,cliente:v.cliente,codigoCliente:v.codigoCliente,representante:v.representante,uf:v.uf,cidade:v.cidade,sem:Number(v.valorSemImpostos??v.valor??0),liq:Number(v.valorLiquido??v.valor??0),origem:v.origem||"Venda",ordem:v.ordem||v.pedido});return arr}
function fillSelectors(){let rr=reps(),opts='<option value="">Todos</option>'+rr.map(r=>`<option>${esc(r)}</option>`).join("");for(const id of ["dashRep","repPedido"]){let x=el(id);if(x){let old=x.value;x.innerHTML=opts;x.value=old}}for(const id of ["vRep","oRep"]){let x=el(id);if(x)x.innerHTML=rr.map(r=>`<option>${esc(r)}</option>`).join("")}let f=el("fCliente");if(f)f.innerHTML=db.clientes.map(c=>`<option value="${c.id}">${esc(c.codigo)} — ${esc(c.razao)}</option>`).join("")}

function renderDashboard(){let mes=val("dashMes"),rp=val("dashRep"),rg=val("dashRegiao"),metric=val("dashMetric")||"sem";let arr=allSales().filter(s=>(!mes||String(s.data).slice(0,7)===mes)&&(!rp||norm(s.representante)===norm(rp))&&(!rg||reg(s.uf)===rg)&&norm(s.status)!=="CANCELADO");let sem=arr.reduce((s,x)=>s+x.sem,0),liq=arr.reduce((s,x)=>s+x.liq,0),chosen=metric==="liq"?"liq":"sem";setText("kSem",money(sem));setText("kLiq",money(liq));setText("kQtd",arr.length);setText("kTicket",money(arr.length?arr.reduce((s,x)=>s+x[chosen],0)/arr.length:0));let ra={},rr={},dd={},cc={};arr.forEach(x=>{let v=x[chosen],r=reg(x.uf),p=x.representante||"Sem representante",d=String(x.data||"").slice(8,10),c=x.cliente||"Cliente";ra[r]=(ra[r]||0)+v;rr[p]=(rr[p]||0)+v;if(d)dd[d]=(dd[d]||0)+v;cc[c]=(cc[c]||0)+v});let rs=Object.entries(ra).sort((a,b)=>b[1]-a[1]),rps=Object.entries(rr).sort((a,b)=>b[1]-a[1]);setText("kRegiao",rs[0]?.[0]||"—");setText("kRep",rps[0]?.[0]||"—");setText("kAlertas",db.alertas.filter(a=>!a.done&&a.data<=today()).length);setText("kFollow",db.followups.filter(f=>!f.done).length);let days=Object.keys(dd).sort((a,b)=>+a-+b);chart("chDia","line",days,days.map(d=>dd[d]),"Vendas");chart("chRep","bar",rps.slice(0,12).map(x=>x[0]),rps.slice(0,12).map(x=>x[1]),"Vendas");chart("chReg","bar",rs.map(x=>x[0]),rs.map(x=>x[1]),"Vendas");setHTML("topClientes",Object.entries(cc).sort((a,b)=>b[1]-a[1]).slice(0,10).map((x,i)=>`<div class="rank"><span>${i+1}. ${esc(x[0])}</span><b>${money(x[1])}</b></div>`).join("")||'<p class="muted">Sem dados no período.</p>')}

function renderClientes(){let q=norm(val("qCliente")),dias=Number(val("diasCliente")||0);let arr=db.clientes.filter(c=>(!q||norm([c.codigo,c.razao,c.cnpj,c.cidade,c.uf,c.tel1,c.tel2,c.representante].join(" ")).includes(q))&&(!dias||Number(c.dias||0)>=dias));setHTML("clientesList",arr.map(c=>`<div class="itemcard"><div class="top"><div><b>${esc(c.codigo)} — ${esc(c.razao)}</b><div class="muted">${esc(c.cidade||"")}/${esc(c.uf||"")} • CNPJ ${esc(c.cnpj||"—")}</div></div><b>${Number(c.dias||0)} dias</b></div><div class="muted">Última compra ${brdate(c.ultima)} • ${money(c.valor)}<br>☎ ${esc(c.tel1||"")} ${c.tel2?" | "+esc(c.tel2):""}</div><div class="actions"><button onclick="openFollow('${c.id}')">📞 Follow-up</button><button onclick="openAlert('${c.id}')">🔔 Alerta</button><button class="whatsapp" onclick="openWhats('${c.id}')">💬 WhatsApp</button><button onclick="openVenda('${c.id}')">💰 Venda</button></div></div>`).join("")||'<div class="card">Nenhum cliente.</div>')}

function renderPedidos(){let q=norm(val("qPedido")),mes=val("mesPedido"),rp=val("repPedido");let arr=db.pedidos.filter(p=>(!q||norm([p.ordem,p.codigoCliente,p.cliente,p.representante].join(" ")).includes(q))&&(!mes||String(p.data).slice(0,7)===mes)&&(!rp||norm(p.representante)===norm(rp)));setText("pSem",money(arr.reduce((s,p)=>s+Number(p.valorSemImpostos??p.valor??0),0)));setText("pLiq",money(arr.reduce((s,p)=>s+Number(p.valorLiquido??p.valor??0),0)));setText("pQtd",arr.length);setHTML("pedidosList",arr.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(p=>`<div class="itemcard"><div class="top"><div><b>Pedido ${esc(p.ordem)} • ${esc(p.codigoCliente||"")} ${esc(p.cliente||"")}</b><div class="muted">${brdate(p.data)} • ${esc(p.representante||"")} • ${esc(p.cidade||"")}/${esc(p.uf||"")}</div></div><div style="text-align:right"><b>${money(p.valorSemImpostos??p.valor)}</b><div class="muted">Líquido ${money(p.valorLiquido??p.valor)}</div></div></div><div class="tags">${p.orcamentoNumero?`<span class="tag">📝 ${esc(p.orcamentoNumero)}</span>`:""}${p.vendaId?'<span class="tag ok">💰 Venda confirmada</span>':`<button class="primary" onclick="confirmVenda('${p.id}')">💰 Confirmar venda</button>`}</div></div>`).join("")||'<div class="card">Nenhum pedido.</div>')}

function renderVendas(){let q=norm(val("qVenda")),mes=val("mesVenda");let arr=db.vendas.filter(v=>(!q||norm([v.ordem,v.codigoCliente,v.cliente,v.representante,v.origem].join(" ")).includes(q))&&(!mes||String(v.data).slice(0,7)===mes));setText("vSem",money(arr.reduce((s,v)=>s+Number(v.valorSemImpostos??v.valor??0),0)));setText("vLiq",money(arr.reduce((s,v)=>s+Number(v.valorLiquido??v.valor??0),0)));setText("vQtd",arr.length);setHTML("vendasList",arr.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(v=>`<div class="itemcard"><div class="top"><div><b>${esc(v.codigoCliente||"")} — ${esc(v.cliente||"")}</b><div class="muted">${brdate(v.data)} • Pedido ${esc(v.ordem||"—")} • ${esc(v.representante||"")}<br>${v.origem?`🔗 ${esc(v.origem)}`:""}</div></div><div style="text-align:right"><b>${money(v.valorSemImpostos??v.valor)}</b><div class="muted">Líquido ${money(v.valorLiquido??v.valor)}</div></div></div></div>`).join("")||'<div class="card">Nenhuma venda.</div>')}

function renderOrcamentos(){let q=norm(val("qOrc")),st=val("statusOrc");let arr=db.orcamentos.filter(o=>(!q||norm([o.numero,o.codigoCliente,o.cliente,o.representante].join(" ")).includes(q))&&(!st||o.status===st));setHTML("orcamentosList",arr.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(o=>`<div class="itemcard"><div class="top"><div><b>${esc(o.numero)} • ${esc(o.codigoCliente)} — ${esc(o.cliente)}</b><div class="muted">${brdate(o.data)} • Validade ${brdate(o.validade)} • ${esc(o.representante||"")}</div></div><b>${money(o.total)}</b></div><div class="tags"><span class="tag">${esc(o.status)}</span>${o.pedidoGerado?`<span class="tag">Pedido ${esc(o.pedidoGerado)}</span>`:""}</div><div class="muted">${(o.itens||[]).map(i=>`${esc(i.descricao)} • ${i.qtd} x ${money(i.preco)}`).join("<br>")}</div><div class="actions">${!["Virou pedido","Venda concluída"].includes(o.status)?`<button onclick="approveOrc('${o.id}')">✅ Aprovar</button><button class="primary" onclick="openConvert('${o.id}')">🧾 Virar pedido</button>`:""}<button class="whatsapp" onclick="whatsOrc('${o.id}')">💬 WhatsApp</button></div></div>`).join("")||'<div class="card">Nenhum orçamento.</div>')}

function renderFollow(){setHTML("followList",db.followups.sort((a,b)=>String(a.data).localeCompare(String(b.data))).map(f=>{let c=clienteById(f.clienteId);return`<div class="itemcard ${f.done?"muted":""}"><b>${esc(c?.codigo||"")} ${esc(c?.razao||"Cliente")}</b><div class="muted">${brdate(f.data)} • ${esc(f.texto)}</div><button onclick="toggleFollow('${f.id}')">${f.done?"Reabrir":"Concluir"}</button></div>`}).join("")||'<div class="card">Nenhum follow-up.</div>')}
function renderAlerts(){setHTML("alertList",db.alertas.sort((a,b)=>String(a.data).localeCompare(String(b.data))).map(a=>{let c=clienteById(a.clienteId);return`<div class="itemcard ${a.done?"muted":""}"><b>🔔 ${esc(c?.codigo||"")} ${esc(c?.razao||"Cliente")}</b><div class="muted">${brdate(a.data)} • ${esc(a.prioridade)} • ${esc(a.texto)}</div><button onclick="toggleAlert('${a.id}')">${a.done?"Reabrir":"Concluir"}</button></div>`}).join("")||'<div class="card">Nenhum alerta.</div>')}

function renderMetas(){let q=norm(val("qMeta")),sup=val("supMeta"),st=val("statusMeta"),base=db.apuracaoMetas||[];let sups=[...new Set(base.map(x=>x.supervisor).filter(Boolean))].sort(),se=el("supMeta");if(se){let old=se.value;se.innerHTML='<option value="">Todos os supervisores</option>'+sups.map(s=>`<option>${esc(s)}</option>`).join("");se.value=old}let arr=base.map(x=>({...x,pct:Number(x.meta)>0?Number(x.vrAtingido)/Number(x.meta)*100:0,falta:Math.max(Number(x.meta||0)-Number(x.vrAtingido||0),0)})).filter(x=>(!q||norm([x.representante,x.razaoSocial,x.supervisor].join(" ")).includes(q))&&(!sup||x.supervisor===sup)&&(!st||(st==="sim"&&x.pct>=100)||(st==="nao"&&x.pct<100)||(st==="80"&&x.pct>=80))).sort((a,b)=>b.pct-a.pct);let mt=base.reduce((s,x)=>s+Number(x.meta||0),0),at=base.reduce((s,x)=>s+Number(x.vrAtingido||0),0);setText("mMeta",money(mt));setText("mAtingido",money(at));setText("mFalta",money(Math.max(mt-at,0)));setHTML("metaBody",arr.map((x,i)=>`<tr><td>${i+1}</td><td class="${x.pct>=100?"statusok":"statusno"}">${x.pct>=100?"Sim":"Não"}</td><td><b>${esc(x.representante)}</b></td><td>${esc(x.razaoSocial||"")}</td><td>${money(x.meta)}</td><td>${money(x.vrAtingido)}</td><td>${money(x.falta)}</td><td><b>${x.pct.toFixed(1)}%</b><div class="progress"><div class="fill" style="width:${Math.min(x.pct,100)}%"></div></div></td><td>${esc(x.supervisor||"")}</td></tr>`).join("")||'<tr><td colspan="9">Importe a planilha de Apuração das Metas.</td></tr>');chart("chMeta","bar",arr.slice(0,20).map(x=>x.representante),arr.slice(0,20).map(x=>Number(x.pct.toFixed(2))),"% da meta",true)}

function openVenda(id){fillSelectors();for(const x of ["vCodigo","vCliente","vClienteId","vOrdem","vValorSem","vValorLiq","vObs"])if(el(x))el(x).value="";if(el("vData"))el("vData").value=today();if(id){let c=clienteById(id);el("vCodigo").value=c?.codigo||"";lookupVenda()}el("vendaModal")?.classList.add("open")}
function lookupVenda(){let c=clienteByCode(val("vCodigo"));if(el("vCliente"))el("vCliente").value=c?.razao||"";if(el("vClienteId"))el("vClienteId").value=c?.id||"";if(c?.representante&&el("vRep"))el("vRep").value=c.representante}
function saveVenda(){let c=clienteByCode(val("vCodigo"));if(!c)return alert("Cliente não encontrado.");db.vendas.push({id:uid(),data:val("vData"),ordem:val("vOrdem"),clienteId:c.id,codigoCliente:c.codigo,cliente:c.razao,representante:val("vRep")||c.representante,uf:c.uf,cidade:c.cidade,valorSemImpostos:num(val("vValorSem")),valorLiquido:num(val("vValorLiq")),valor:num(val("vValorSem")),origem:"Venda manual",obs:val("vObs")});closeModal("vendaModal");save()}

function openFollow(id){fillSelectors();if(id&&el("fCliente"))el("fCliente").value=id;if(el("fData"))el("fData").value=today();if(el("fTexto"))el("fTexto").value="";el("followModal")?.classList.add("open")}
function saveFollow(){if(!val("fCliente")||!val("fData")||!val("fTexto"))return alert("Preencha os campos.");db.followups.push({id:uid(),clienteId:val("fCliente"),data:val("fData"),texto:val("fTexto"),done:false});closeModal("followModal");save()}
function toggleFollow(id){let x=db.followups.find(f=>f.id===id);if(x)x.done=!x.done;save()}
function openAlert(id){let c=clienteById(id);if(el("aClienteId"))el("aClienteId").value=id;setText("aClienteNome",`${c?.codigo||""} — ${c?.razao||""}`);if(el("aData"))el("aData").value=today();if(el("aTexto"))el("aTexto").value="";el("alertModal")?.classList.add("open")}
function saveAlert(){db.alertas.push({id:uid(),clienteId:val("aClienteId"),data:val("aData"),texto:val("aTexto"),prioridade:val("aPrio"),done:false,notified:false});closeModal("alertModal");save()}
function toggleAlert(id){let x=db.alertas.find(a=>a.id===id);if(x)x.done=!x.done;save()}

function phone(v){let n=String(v||"").replace(/\D/g,"");if((n.length===10||n.length===11)&&!n.startsWith("55"))n="55"+n;return n}
function openWhats(id){let c=clienteById(id),ps=[c?.tel1,c?.tel2].filter(Boolean);if(!ps.length)return alert("Cliente sem telefone.");if(el("waClienteId"))el("waClienteId").value=id;setHTML("waPhone",ps.map((p,i)=>`<option value="${phone(p)}">Telefone ${i+1}: ${esc(p)}</option>`).join(""));if(el("waMsg"))el("waMsg").value="Olá! Tudo bem? Estou entrando em contato para dar continuidade ao nosso atendimento comercial.";el("waModal")?.classList.add("open")}
function sendWhats(){window.open(`https://wa.me/${val("waPhone")}?text=${encodeURIComponent(val("waMsg"))}`,"_blank")}

function openOrcamento(){fillSelectors();for(const x of ["oCodigo","oCliente","oClienteId","oObs"])if(el(x))el(x).value="";if(el("oDesc"))el("oDesc").value=0;if(el("oValidade"))el("oValidade").value=new Date(Date.now()+7*86400000).toISOString().slice(0,10);setHTML("oItens","");addItem();recalcOrc();el("orcModal")?.classList.add("open")}
function lookupOrc(){let c=clienteByCode(val("oCodigo"));if(el("oCliente"))el("oCliente").value=c?.razao||"";if(el("oClienteId"))el("oClienteId").value=c?.id||"";if(c?.representante&&el("oRep"))el("oRep").value=c.representante}
function addItem(){let tb=el("oItens");if(!tb)return;let tr=document.createElement("tr");tr.innerHTML='<td><input class="desc"></td><td><input class="qtd" type="number" value="1" min="1" oninput="recalcOrc()"></td><td><input class="preco" type="number" value="0" step="0.01" oninput="recalcOrc()"></td><td class="sub">R$ 0,00</td><td><button class="danger" onclick="this.closest(\'tr\').remove();recalcOrc()">×</button></td>';tb.appendChild(tr)}
function itensOrc(){return [...(el("oItens")?.querySelectorAll("tr")||[])].map(tr=>({descricao:tr.querySelector(".desc").value.trim(),qtd:num(tr.querySelector(".qtd").value),preco:num(tr.querySelector(".preco").value)})).filter(i=>i.descricao&&i.qtd>0)}
function recalcOrc(){let bruto=0;for(let tr of el("oItens")?.querySelectorAll("tr")||[]){let q=num(tr.querySelector(".qtd").value),p=num(tr.querySelector(".preco").value);bruto+=q*p;tr.querySelector(".sub").textContent=money(q*p)}if(el("oTotal"))el("oTotal").value=money(Math.max(bruto-num(val("oDesc")),0))}
function saveOrc(){let c=clienteByCode(val("oCodigo")),itens=itensOrc();if(!c)return alert("Cliente não encontrado.");if(!itens.length)return alert("Adicione itens.");let bruto=itens.reduce((s,i)=>s+i.qtd*i.preco,0),desconto=num(val("oDesc"));db.orcamentos.push({id:uid(),numero:`ORC-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,data:today(),validade:val("oValidade"),clienteId:c.id,codigoCliente:c.codigo,cliente:c.razao,representante:val("oRep")||c.representante,cidade:c.cidade,uf:c.uf,itens,desconto,total:Math.max(bruto-desconto,0),observacao:val("oObs"),status:"Em aberto",pedidoGerado:"",vendaId:""});closeModal("orcModal");save()}
function approveOrc(id){let o=db.orcamentos.find(x=>x.id===id);if(o)o.status="Aprovado";save()}
function openConvert(id){if(el("convOrcId"))el("convOrcId").value=id;if(el("convNumero"))el("convNumero").value="";if(el("convData"))el("convData").value=today();el("pedidoModal")?.classList.add("open")}
function convertOrc(){let o=db.orcamentos.find(x=>x.id===val("convOrcId"));if(!o)return;let numero=val("convNumero")||`PED-${String(Date.now()).slice(-6)}`;if(db.pedidos.some(p=>String(p.ordem)===String(numero)))return alert("Pedido já existe.");db.pedidos.push({id:uid(),ordem:numero,data:val("convData"),clienteId:o.clienteId,codigoCliente:o.codigoCliente,cliente:o.cliente,representante:o.representante,cidade:o.cidade,uf:o.uf,valorSemImpostos:o.total,valorLiquido:o.total,valor:o.total,status:"Digitado",origem:"Orçamento",orcamentoId:o.id,orcamentoNumero:o.numero,itens:o.itens,vendaId:""});o.status="Virou pedido";o.pedidoGerado=numero;closeModal("pedidoModal");save()}
function confirmVenda(id){let p=db.pedidos.find(x=>x.id===id);if(!p||p.vendaId)return;let o=p.orcamentoId?db.orcamentos.find(x=>x.id===p.orcamentoId):null,v={id:uid(),data:today(),ordem:p.ordem,pedidoId:p.id,clienteId:p.clienteId,codigoCliente:p.codigoCliente,cliente:p.cliente,representante:p.representante,cidade:p.cidade,uf:p.uf,valorSemImpostos:Number(p.valorSemImpostos??p.valor??0),valorLiquido:Number(p.valorLiquido??p.valor??0),valor:Number(p.valorSemImpostos??p.valor??0),origem:o?`Orçamento ${o.numero} → Pedido ${p.ordem}`:`Pedido ${p.ordem}`,orcamentoId:o?.id||"",orcamentoNumero:o?.numero||"",itens:p.itens||[]};db.vendas.push(v);p.vendaId=v.id;p.status="Venda confirmada";if(o){o.status="Venda concluída";o.vendaId=v.id}save()}
function whatsOrc(id){let o=db.orcamentos.find(x=>x.id===id),c=clienteById(o?.clienteId),p=phone(c?.tel1||c?.tel2);if(!p)return alert("Cliente sem telefone.");let msg=`Olá! Segue o orçamento ${o.numero}:\n\n${(o.itens||[]).map(i=>`• ${i.descricao}: ${i.qtd} x ${money(i.preco)}`).join("\n")}\n\nTotal: ${money(o.total)}\nValidade: ${brdate(o.validade)}`;window.open(`https://wa.me/${p}?text=${encodeURIComponent(msg)}`,"_blank")}

function readFile(id,cb){let f=el(id)?.files?.[0];if(!f)return alert("Escolha um arquivo.");let r=new FileReader();r.onload=e=>{try{cb(XLSX.read(e.target.result,{type:"array",raw:true,cellDates:true}))}catch(err){console.error(err);alert("Erro ao ler arquivo: "+err.message)}};r.readAsArrayBuffer(f)}
function importClientes(){readFile("fileClientes",wb=>{let rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""}),map=new Map(db.clientes.map(c=>[String(c.codigo),c]));for(let row of rows){let get=names=>{for(let n of names)for(let k of Object.keys(row))if(header(k)===header(n))return row[k];return""},codigo=get(["CODIGO CLIENTE","CÓDIGO CLIENTE","CODIGO"]);if(codigo==="")continue;let old=map.get(String(codigo));map.set(String(codigo),{id:old?.id||uid(),codigo,razao:get(["RAZAO CLIENTE","RAZÃO CLIENTE","CLIENTE"]),cnpj:get(["CNPJ"]),representante:get(["REPRESENTANTE"]),cidade:get(["CIDADE"]),uf:get(["UF"]),ultima:dateVal(get(["ULTIMA COMPRA","ÚLTIMA COMPRA"])),dias:num(get(["DIAS SEM COMPRAR"])),valor:num(get(["VALOR ULTIMA COMPRA","VALOR ÚLTIMA COMPRA"])),responsavel:get(["RESPONSAVEL","RESPONSÁVEL"]),tel1:get(["TELEFONE 1","TELEFONE"]),tel2:get(["TELEFONE 2"])})}db.clientes=[...map.values()];save();setHTML("msgClientes",`✅ <b>${db.clientes.length}</b> clientes disponíveis.`)})}

function importPedidos(){readFile("filePedidos",wb=>{let map=new Map(db.pedidos.map(p=>[String(p.ordem),p])),diag=[],lidos=0;for(let sn of wb.SheetNames){let raw=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:"",raw:true}),hr=findHeader(raw,[["ORDEM"],["VR TOTAL","VALOR","RAZAO SOCIAL"]]);if(hr<0){diag.push(`${sn}: cabeçalho não encontrado`);continue}let h=raw[hr],cO=col(h,["Ordem"]),cR=col(h,["Razão Social","Razao Social","Cliente"]),cD=col(h,["Digitação","Digitacao"]),cF=col(h,["Faturamento"]),cLib=col(h,["Data Liberação/Crédito","Data Liberacao/Credito"]),cS=col(h,["Vr Total (s/impostos)","Vr Total s/impostos"]),cL=col(h,["Vr Total (Líquido)","Vr Total (Liquido)"]),cRep=col(h,["Representante"]),cCod=col(h,["Código Cliente","Codigo Cliente"]),cCid=col(h,["Cidade"]),cUf=col(h,["UF"]);diag.push(`${sn}: Ordem=${cO>=0?"OK":"NÃO"} | Sem impostos=${cS>=0?h[cS]:"NÃO"} | Líquido=${cL>=0?h[cL]:"NÃO"}`);if(cO<0)continue;for(let i=hr+1;i<raw.length;i++){let row=raw[i],ord=row[cO];if(ord===""||ord==null||!/\d/.test(String(ord)))continue;let key=String(ord).trim(),old=map.get(key),cod=cCod>=0?row[cCod]:"",c=cod?clienteByCode(cod):null;map.set(key,{id:old?.id||uid(),ordem:key,data:dateVal(cD>=0?row[cD]:"")||old?.data||"",faturamento:dateVal(cF>=0?row[cF]:""),liberacao:dateVal(cLib>=0?row[cLib]:""),codigoCliente:cod||old?.codigoCliente||c?.codigo||"",cliente:(cR>=0?String(row[cR]||"").trim():"")||old?.cliente||c?.razao||"",representante:(cRep>=0?String(row[cRep]||"").trim():"")||old?.representante||c?.representante||"",cidade:(cCid>=0?String(row[cCid]||"").trim():"")||old?.cidade||c?.cidade||"",uf:(cUf>=0?String(row[cUf]||"").trim():"")||old?.uf||c?.uf||"",valorSemImpostos:cS>=0?num(row[cS]):0,valorLiquido:cL>=0?num(row[cL]):0,valor:cS>=0?num(row[cS]):0,status:old?.status||"",vendaId:old?.vendaId||"",orcamentoId:old?.orcamentoId||"",orcamentoNumero:old?.orcamentoNumero||""});lidos++}}db.pedidos=[...map.values()];save();let ts=db.pedidos.reduce((s,p)=>s+Number(p.valorSemImpostos||0),0),tl=db.pedidos.reduce((s,p)=>s+Number(p.valorLiquido||0),0);setHTML("msgPedidos",`✅ <b>${lidos}</b> linhas lidas • <b>${db.pedidos.length}</b> pedidos únicos<br>💰 Sem impostos: <b>${money(ts)}</b><br>🧾 Líquido: <b>${money(tl)}</b><details><summary>Colunas reconhecidas</summary>${diag.map(x=>`<div>${esc(x)}</div>`).join("")}</details>`)})}

function importMetas(){readFile("fileMetas",wb=>{let linhas=[],diag=[];for(let sn of wb.SheetNames){let raw=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:"",raw:true}),hr=findHeader(raw,[["ATINGIDO"],["REPRESENTANTE"],["META","VR ATINGIDO"]]);if(hr<0){diag.push(`${sn}: cabeçalho não encontrado`);continue}let h=raw[hr],ca=col(h,["Atingido"]),cr=col(h,["Representante"]),cz=col(h,["Razão Social","Razao Social"]),cm=col(h,["Meta"]),cv=col(h,["Vr Atingido","Valor Atingido"]),cs=col(h,["Nome do Supervisor","Supervisor"]);diag.push(`${sn}: Atingido=${ca>=0?h[ca]:"NÃO"} | Representante=${cr>=0?h[cr]:"NÃO"} | Razão=${cz>=0?h[cz]:"NÃO"} | Meta=${cm>=0?h[cm]:"NÃO"} | Vr Atingido=${cv>=0?h[cv]:"NÃO"} | Supervisor=${cs>=0?h[cs]:"NÃO"}`);for(let i=hr+1;i<raw.length;i++){let row=raw[i],rep=cr>=0?String(row[cr]||"").trim():"",rz=cz>=0?String(row[cz]||"").trim():"";if(!rep&&!rz)continue;linhas.push({atingido:ca>=0?String(row[ca]||"").trim():"",representante:rep,razaoSocial:rz,meta:cm>=0?num(row[cm]):0,vrAtingido:cv>=0?num(row[cv]):0,supervisor:cs>=0?String(row[cs]||"").trim():""})}}db.apuracaoLinhas=linhas;let map=new Map();for(let x of linhas){let k=norm(x.representante||x.razaoSocial);if(!k)continue;if(!map.has(k))map.set(k,{...x});else{let a=map.get(k);a.meta=Math.max(a.meta,x.meta);a.vrAtingido=Math.max(a.vrAtingido,x.vrAtingido);if(!a.razaoSocial)a.razaoSocial=x.razaoSocial;if(!a.supervisor)a.supervisor=x.supervisor}}db.apuracaoMetas=[...map.values()].map(x=>({...x,atingido:x.meta>0&&x.vrAtingido>=x.meta?"Sim":"Não"}));save();let mt=db.apuracaoMetas.reduce((s,x)=>s+x.meta,0),va=db.apuracaoMetas.reduce((s,x)=>s+x.vrAtingido,0);setHTML("msgMetas",`✅ <b>${linhas.length}</b> linhas • <b>${db.apuracaoMetas.length}</b> representantes únicos<br>🎯 Meta: <b>${money(mt)}</b> • 💰 Vr Atingido: <b>${money(va)}</b><details><summary>Colunas reconhecidas</summary>${diag.map(x=>`<div>${esc(x)}</div>`).join("")}</details>`)})}

function backup(){let b=new Blob([JSON.stringify({app:"Gestor Comercial",date:new Date().toISOString(),dados:db},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`Backup_Gestor_${today()}.json`;a.click()}
function restoreBackup(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=x=>{try{let p=JSON.parse(x.target.result),d=p.dados||p;db=d;for(const k of ["clientes","pedidos","vendas","orcamentos","followups","alertas","apuracaoLinhas","apuracaoMetas"])if(!Array.isArray(db[k]))db[k]=[];save();alert("Backup restaurado.")}catch(err){alert("Backup inválido.")}};r.readAsText(f)}
function exportExcel(){let wb=XLSX.utils.book_new();for(const [n,d] of [["Clientes",db.clientes],["Pedidos",db.pedidos],["Vendas",db.vendas],["Orçamentos",db.orcamentos.map(o=>({...o,itens:JSON.stringify(o.itens)}))],["Apuração Metas",db.apuracaoMetas],["Follow-ups",db.followups],["Alertas",db.alertas]])XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),n);XLSX.writeFile(wb,"Gestor_Comercial.xlsx")}
async function enableNotifications(){if(!("Notification"in window))return alert("Navegador sem suporte.");let p=await Notification.requestPermission();setText("notifyBtn",p==="granted"?"🔔 Notificações ativadas":"🔕 Bloqueadas")}
function checkNotifications(){if(!("Notification"in window)||Notification.permission!=="granted")return;let changed=false;for(let a of db.alertas.filter(a=>!a.done&&!a.notified&&a.data<=today())){let c=clienteById(a.clienteId);new Notification("Follow-up comercial",{body:`${c?.razao||"Cliente"} — ${a.texto}`});a.notified=true;changed=true}if(changed)save(false)}

function render(){fillSelectors();renderDashboard();renderClientes();renderPedidos();renderVendas();renderOrcamentos();renderFollow();renderAlerts();renderMetas();checkNotifications()}
render();setInterval(checkNotifications,60000);